kind: pipeline
type: docker
name: docs-web

trigger:
  branch:
    - master

volumes:
  - name: pnpm-cache
    host:
      path: /var/lib/drone-cache/pnpm/docs-web

steps:

  - name: restore-pnpm-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: pnpm-cache
        path: /cache
    settings:
      restore: true
      mount:
        - /cache/pnpm-store

  - name: build and package
    image: node:20-alpine
    volumes:
      - name: pnpm-cache
        path: /cache
    commands:
      - ls -a
      - corepack enable
      - corepack prepare pnpm@9 --activate
      - pnpm config set store-dir /cache/pnpm-store
      - pnpm config set registry https://registry.npmmirror.com/
      - pnpm -w install --frozen-lockfile --filter './apps/docs-web...'
      - pnpm --filter ./apps/docs-web run build
      - pnpm deploy --filter ./apps/docs-web --node-linker=hoisted /drone/src/docs-web-deploy
      - cd /drone/src/docs-web-deploy
      - tar -czf /drone/src/docs-web.tar.gz ./*
      - ls /drone/src/

  - name: rebuild-pnpm-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: pnpm-cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - /cache/pnpm-store

  - name: scp
    image: appleboy/drone-scp
    settings:
      debug: false
      source:
        - docs-web.tar.gz
      host:
        from_secret: CURRENT_HOST
      username: root
      port: 22
      password:
        from_secret: SSH_PWD
      target: /temp/app/

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: CURRENT_HOST
      username: root
      password:
        from_secret: SSH_PWD
      port: 22
      command_timeout: 2m
      script:
        - rm -rf /data/app/docs-web
        - mkdir -p /data/app/docs-web
        - cd /temp/app
        - ls /temp/app -a
        - tar xzf docs-web.tar.gz -C /data/app/docs-web
        - rm -rf /temp/app/docs-web.tar.gz
        - cd /data/app/docs-web
        - ls /data/app/docs-web -a
